[[docs]]
  name = "导航站"
  weight = 10
  identifier = "webstack"
  url = "/docs/webstack/"

[[docs]]
  name = "文档库"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[docs]]
  name = "博客部署"
  weight = 90
  identifier = "halo"
  url = "/docs/halo/"

[[main]]
  name = "文档"
  url = "/docs/help/start/"
# url = "/docs/1.0/doks/introduction/"
  weight = 10

[[main]]
  name = "博客"
  url = "/blog/"
  weight = 20

[[main]]
  name = "教程"
  weight = 30
  identifier = "get-started"
  url = "/docs/help/start/"

[[main]]
  name = "搭建"
  weight = 40
  identifier = "start"
  url = "/docs/help/start/"
  parent = "get-started"

[[main]]
  name = "部署"
  weight = 50
  identifier = "pull"
  url = "/docs/help/pull/"
  parent = "get-started"

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
